import type { CSSProperties } from "react";

/** Co-located styles for AgentPicker. */
export const s = {
  root: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    position: "relative",
  } satisfies CSSProperties,
  selectWrap: {
    position: "relative",
    display: "inline-block",
  } satisfies CSSProperties,
  trigger: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 13px",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-primary)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 6,
    cursor: "pointer",
  } satisfies CSSProperties,
  panel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    minWidth: 240,
    maxHeight: 320,
    overflowY: "auto",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 9,
    boxShadow: "var(--shadow-modal)",
    padding: 8,
    zIndex: 40,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "7px 8px",
    borderRadius: 6,
    border: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 500,
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  checkbox: (checked: boolean): CSSProperties => ({
    width: 15,
    height: 15,
    flexShrink: 0,
    borderRadius: 4,
    border: "1.5px solid " + (checked ? "var(--accent)" : "var(--border-strong)"),
    background: checked ? "var(--accent)" : "transparent",
    display: "grid",
    placeItems: "center",
  }),
  emptyState: {
    padding: "10px 8px",
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "3px 6px 6px",
  } satisfies CSSProperties,
  headerTitle: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  headerClear: {
    fontSize: 12,
    fontWeight: 500,
    color: "var(--accent)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "2px 4px",
  } satisfies CSSProperties,
  runBtn: (disabled: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    marginTop: 6,
    padding: "9px 12px",
    fontSize: 13,
    fontWeight: 600,
    color: disabled ? "var(--text-muted)" : "#fff",
    background: disabled ? "var(--bg-subtle)" : "var(--accent)",
    border: "none",
    borderRadius: 7,
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.65 : 1,
  }),
  configureBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    width: "100%",
    marginTop: 4,
    padding: "7px 8px",
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-muted)",
    background: "transparent",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  } satisfies CSSProperties,
} satisfies Record<string, CSSProperties | ((checked: boolean) => CSSProperties)>;
