import type { CSSProperties } from "react";

/** Co-located styles for ConfigureRun (T13). */
export const s = {
  page: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
    padding: "28px 32px",
    maxWidth: 720,
  } satisfies CSSProperties,
  h1: {
    fontSize: 20,
    fontWeight: 600,
    color: "var(--text-primary)",
    margin: 0,
  } satisfies CSSProperties,
  selectorRow: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  selectorCol: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    flex: "1 1 260px",
    minWidth: 220,
  } satisfies CSSProperties,
  label: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
    textTransform: "uppercase",
    letterSpacing: "0.02em",
  } satisfies CSSProperties,
  agentsSection: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  agentsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  selectAllBtn: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--accent)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "2px 4px",
  } satisfies CSSProperties,
  agentList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  agentCard: (accent: string, checked: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    width: "100%",
    textAlign: "left",
    padding: "13px 15px",
    borderRadius: 11,
    cursor: "pointer",
    border: "1px solid " + (checked ? accent : "var(--border)"),
    background: checked ? accent + "14" : "var(--bg-elevated)",
  }),
  cardCheck: (accent: string, checked: boolean): CSSProperties => ({
    width: 18,
    height: 18,
    flexShrink: 0,
    marginTop: 1,
    borderRadius: 5,
    border: "1.5px solid " + (checked ? accent : "var(--border-strong)"),
    background: checked ? accent : "transparent",
    display: "grid",
    placeItems: "center",
  }),
  iconTile: (accent: string): CSSProperties => ({
    width: 30,
    height: 30,
    flexShrink: 0,
    borderRadius: 8,
    background: accent + "22",
    color: accent,
    display: "grid",
    placeItems: "center",
  }),
  cardText: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  cardName: {
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  cardDesc: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  cardEstimate: {
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    marginTop: 1,
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
  } satisfies CSSProperties,
  summaryLine: {
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
  } satisfies CSSProperties,
  noSelection: {
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  approxNote: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  launchRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
  } satisfies CSSProperties,
  launchInfo: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  } satisfies CSSProperties,
} satisfies Record<string, CSSProperties | ((accent: string, checked: boolean) => CSSProperties) | ((accent: string) => CSSProperties)>;
