import type { CSSProperties } from "react";

/** Co-located styles for the Onboarding Tour page. */
export const s = {
  layout: {
    display: "flex",
    alignItems: "flex-start",
    gap: 0,
  } satisfies CSSProperties,
  nav: {
    width: 190,
    flexShrink: 0,
    padding: "24px 16px",
    position: "sticky",
    top: 0,
  } satisfies CSSProperties,
  navLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    marginBottom: 10,
    paddingLeft: 10,
  } satisfies CSSProperties,
  navList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    listStyle: "none",
    margin: 0,
    padding: 0,
  } satisfies CSSProperties,
  navLink: {
    display: "block",
    padding: "6px 10px",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
    borderLeft: "2px solid transparent",
    textDecoration: "none",
  } satisfies CSSProperties,
  navLinkActive: {
    color: "var(--accent-text)",
    borderLeft: "2px solid var(--accent)",
    background: "var(--accent-bg)",
    fontWeight: 600,
  } satisfies CSSProperties,
  main: {
    flex: 1,
    minWidth: 0,
    padding: "24px 32px 60px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  title: {
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  repoName: {
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  subtitle: {
    fontSize: 14,
    color: "var(--text-secondary)",
    marginTop: 4,
  } satisfies CSSProperties,
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  degradedBanner: {
    background: "var(--warn-bg)",
    color: "var(--warn)",
    border: "1px solid var(--warn)",
  } satisfies CSSProperties,
  staleBanner: {
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    border: "1px solid var(--accent)",
  } satisfies CSSProperties,
  bannerBody: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 16px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  cardIcon: {
    width: 26,
    height: 26,
    borderRadius: 6,
    display: "grid",
    placeItems: "center",
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    flexShrink: 0,
  } satisfies CSSProperties,
  cardTitle: {
    fontSize: 14,
    fontWeight: 650,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  cardBody: {
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  narrative: {
    fontSize: 14,
    lineHeight: 1.6,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  inlineCode: {
    fontFamily: "monospace",
    fontSize: "0.92em",
    padding: "1px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  inlineCodeLink: {
    fontFamily: "monospace",
    fontSize: "0.92em",
    padding: "1px 6px",
    borderRadius: 4,
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    textDecoration: "underline",
    cursor: "pointer",
    border: "none",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 7,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  rowMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  rowPath: {
    fontFamily: "monospace",
    fontSize: 13,
    color: "var(--text-primary)",
    display: "flex",
    alignItems: "baseline",
    gap: 6,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  rowWhy: {
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  orderBadge: {
    width: 20,
    height: 20,
    borderRadius: 99,
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    fontSize: 11,
    fontWeight: 700,
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  commandRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 7,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  commandText: {
    flex: 1,
    minWidth: 0,
    fontFamily: "monospace",
    fontSize: 13,
    color: "var(--text-primary)",
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  commandNote: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginTop: 2,
  } satisfies CSSProperties,
  taskTitle: {
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  taskDetail: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    marginTop: 2,
  } satisfies CSSProperties,
  copyStatus: {
    fontSize: 11,
    color: "var(--ok)",
  } satisfies CSSProperties,
  visuallyHidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0,0,0,0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
  emptyRow: {
    fontSize: 13,
    color: "var(--text-muted)",
    padding: "8px 4px",
  } satisfies CSSProperties,
  loadingStack: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
} as const;
